version: 2
build:
  image: "ubuntu-22.04"   # use 'build.image' instead of 'build.os'
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      requirements:
        - requirements.txt