version: 2
build:
  image: "ubuntu-22.04"  # replaced 'os' with 'image'
  tools:
    python: "3.10"
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - method: pip
      requirements:
        - requirements.txt
